export const headerCountries = [
    { title: "Afghanistan" },
    { title: "Albania" },
    { title: "Algeria" },
    { title: "Andorra" },
    { title: "Angola" },
    { title: "Antigua and Barbuda" },
    { title: "Argentina" },
    { title: "Armenia" },
    { title: "Australia" },
    { title: "Austria" },
    { title: "Azerbaijan" },
    { title: "Bahamas" },
    { title: "Bahrain" },
    { title: "Bangladesh" },
    { title: "Barbados" },
    { title: "Belarus" },
    { title: "Belgium" },
    { title: "Belize" },
    { title: "Benin" },
    { title: "Bhutan" },
    { title: "Bolivia" },
    { title: "Bosnia and Herzegovina" },
    { title: "Botswana" },
    { title: "Brazil" },
    { title: "Brunei" },
    { title: "Bulgaria" },
    { title: "Burkina Faso" },
    { title: "Burundi" },
    { title: "Côte d'Ivoire" },
    { title: "Cabo Verde" },
    { title: "Cambodia" },
    { title: "Cameroon" },
    { title: "Canada" },
    { title: "Central African Republic" },
    { title: "Chad" },
    { title: "Chile" },
    { title: "China" },
    { title: "Colombia" },
    { title: "Comoros" },
    { title: "Congo" },
    { title: "Costa Rica" },
    { title: "Croatia" },
    { title: "Cuba" },
    { title: "Cyprus" },
    { title: "Czech Republic" },
    { title: "Democratic Republic of the Congo" },
    { title: "Denmark" },
    { title: "Djibouti" },
    { title: "Dominica" },
    { title: "Dominican Republic" },
    { title: "Ecuador" },
    { title: "Egypt" },
    { title: "El Salvador" },
    { title: "Equatorial Guinea" },
    { title: "Eritrea" },
    { title: "Estonia" },
    { title: "Eswatini" },
    { title: "Ethiopia" },
    { title: "Fiji" },
    { title: "Finland" },
    { title: "France" },
    { title: "Gabon" },
    { title: "Gambia" },
    { title: "Georgia" },
    { title: "Germany" },
    { title: "Ghana" },
    { title: "Greece" },
    { title: "Grenada" },
    { title: "Guatemala" },
    { title: "Guinea" },
    { title: "Guinea-Bissau" },
    { title: "Guyana" },
    { title: "Haiti" },
    { title: "Holy See" },
    { title: "Honduras" },
    { title: "Hungary" },
    { title: "Iceland" },
    { title: "India" },
    { title: "Indonesia" },
    { title: "Iran" },
    { title: "Iraq" },
    { title: "Ireland" },
    { title: "Israel" },
    { title: "Italy" },
    { title: "Jamaica" },
    { title: "Japan" },
    { title: "Jordan" },
    { title: "Kazakhstan" },
    { title: "Kenya" },
    { title: "Kiribati" },
    { title: "Kuwait" },
    { title: "Kyrgyzstan" },
    { title: "Laos" },
    { title: "Latvia" },
    { title: "Lebanon" },
    { title: "Lesotho" },
    { title: "Liberia" },
    { title: "Libya" },
    { title: "Liechtenstein" },
    { title: "Lithuania" },
    { title: "Luxembourg" },
    { title: "Madagascar" },
    { title: "Malawi" },
    { title: "Malaysia" },
    { title: "Maldives" },
    { title: "Mali" },
    { title: "Malta" },
    { title: "Marshall Islands" },
    { title: "Mauritania" },
    { title: "Mauritius" },
    { title: "Mexico" },
    { title: "Micronesia" },
    { title: "Moldova" },
    { title: "Monaco" },
    { title: "Mongolia" },
    { title: "Montenegro" },
    { title: "Morocco" },
    { title: "Mozambique" },
    { title: "Myanmar" },
    { title: "Namibia" },
    { title: "Nauru" },
    { title: "Nepal" },
    { title: "Netherlands" },
    { title: "New Zealand" },
    { title: "Nicaragua" },
    { title: "Niger" },
    { title: "Nigeria" },
    { title: "North Korea" },
    { title: "North Macedonia" },
    { title: "Norway" },
    { title: "Oman" },
    { title: "Pakistan" },
    { title: "Palau" },
    { title: "Palestine State" },
    { title: "Panama" },
    { title: "Papua New Guinea" },
    { title: "Paraguay" },
    { title: "Peru" },
    { title: "Philippines" },
    { title: "Poland" },
    { title: "Portugal" },
    { title: "Qatar" },
    { title: "Romania" },
    { title: "Russia" },
    { title: "Rwanda" },
    { title: "Saint Kitts and Nevis" },
    { title: "Saint Lucia" },
    { title: "Saint Vincent and the Grenadines" },
    { title: "Samoa" },
    { title: "San Marino" },
    { title: "Sao Tome and Principe" },
    { title: "Saudi Arabia" },
    { title: "Senegal" },
    { title: "Serbia" },
    { title: "Seychelles" },
    { title: "Sierra Leone" },
    { title: "Singapore" },
    { title: "Slovakia" },
    { title: "Slovenia" },
    { title: "Solomon Islands" },
    { title: "Somalia" },
    { title: "South Africa" },
    { title: "South Korea" },
    { title: "South Sudan" },
    { title: "Spain" },
    { title: "Sri Lanka" },
    { title: "Sudan" },
    { title: "Suriname" },
    { title: "Sweden" },
    { title: "Switzerland" },
    { title: "Syria" },
    { title: "Tajikistan" },
    { title: "Tanzania" },
    { title: "Thailand" },
    { title: "Timor-Leste" },
    { title: "Togo" },
    { title: "Tonga" },
    { title: "Trinidad and Tobago" },
    { title: "Tunisia" },
    { title: "Turkey" },
    { title: "Turkmenistan" },
    { title: "Tuvalu" },
    { title: "Uganda" },
    { title: "Ukraine" },
    { title: "United Arab Emirates" },
    { title: "United Kingdom" },
    { title: "United States of America" },
    { title: "Uruguay" },
    { title: "Uzbekistan" },
    { title: "Vanuatu" },
    { title: "Venezuela" },
    { title: "Vietnam" },
    { title: "Yemen" },
    { title: "Zambia" },
    { title: "Zimbabwe" }
  ];